version: '2'
services:
  awsie:
    build: .
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws
      - /app/awsie.egg-info
      - /app/build
      - /app/dist
      - /app/.pytest_cache
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
